version: '3'

services:
  bot:
    build: .
    container_name: telegram-llm-bot
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
